Fix make distcheck
cp: cannot create regular file './test3.log': Permission denied

This is happening because, under a distcheck “install-and-test” run, the
test script is being executed from the installed prefix – which isn’t
writable.

The simplest fix is to stop copying the data file into the (non-writable)
working directory and just refer to it in place via srcdir.

Secondly,
ERROR: files left in build directory after distclean:
./auparse/test/run_auparselol_test.sh
./auparse/test/run_auparse_tests.sh
make[1]: *** [Makefile:755: distcleancheck] Error 1

This is hitting Automake’s “left-over files” check because those two
scripts get generated (from .in templates) but aren’t being removed by
make distclean. By default:

    CLEANFILES only affects make clean

    DISTCLEANFILES is what make distclean (and thus make distcheck) uses to know what to wipe out
    gnu.org

So, we need to assign the files to DISTCLEANFILES so they get deleted by
make distcheck.